version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "@grafana/*"
      dev-dependencies:
        patterns:
          - "@grafana/e2e*"

    # Ignore most dependencies that are maintained via the create-plugin tool
    # See https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/common/package.json
    ignore:
      - dependency-name: "@babel/core"
      - dependency-name: "@emotion/css"
      - dependency-name: "@grafana/eslint-config"
      - dependency-name: "@grafana/tsconfig"
      - dependency-name: "@swc/core"
      - dependency-name: "@swc/helpers"
      - dependency-name: "@swc/jest"
      - dependency-name: "@testing-library/jest-dom"
      - dependency-name: "@testing-library/react"
      - dependency-name: "@types/jest"
      - dependency-name: "@types/lodash"
      - dependency-name: "@types/node"
      - dependency-name: "@types/react-router-dom"
      - dependency-name: react
      - dependency-name: react-dom
      - dependency-name: react-router-dom
      - dependency-name: rxjs
      - dependency-name: tslib
      - dependency-name: copy-webpack-plugin
      - dependency-name: css-loader
      - dependency-name: eslint-webpack-plugin
      - dependency-name: fork-ts-checker-webpack-plugin
      - dependency-name: glob
      - dependency-name: identity-obj-proxy
      - dependency-name: jest
      - dependency-name: jest-environment-jsdom
      - dependency-name: prettier
      - dependency-name: replace-in-file-webpack-plugin
      - dependency-name: sass
      - dependency-name: sass-loader
      - dependency-name: style-loader
      - dependency-name: swc-loader
      - dependency-name: ts-node
      - dependency-name: tsconfig-paths
      - dependency-name: typescript
      - dependency-name: webpack
      - dependency-name: webpack-cli
      - dependency-name: webpack-livereload-plug
